### ISSUE TITLE
can't load this mod(

### ISSUE THREAD

**Issue by 5ur3z** [mindstorm38/fabric-webstreamer#10]
![S(BEP@$UM7 7~_DUT7$1$Y7](https://user-images.githubusercontent.com/89332189/203879005-6de85983-d099-47a8-b853-414d44a299d2.png)

**Comment by mindstorm38** [comment]
Looks like the mod's file is corrupted 🤔

**Comment by 5ur3z** [comment]
nope, I'm using a sync tool that can sync mods folder between server and client.
some other players can join the server successfully.
hmm, maybe I should let them try again.
