### ISSUE TITLE
Unable to play streaming video

### ISSUE THREAD

**Issue by RainbowFishNetwork** [mindstorm38/fabric-webstreamer#12]
I set up an M3U8 server to stream through OBS and play it normally when using potplayer, but when I paste the url into the game, it keeps black.
Does this have anything to do with coding patterns and color patterns?
（Using Google Translate may cause grammatical errors）
![image](https://user-images.githubusercontent.com/114065726/205847462-64f70921-3d13-49ba-9e6b-2a4731aceebd.png)
![image](https://user-images.githubusercontent.com/114065726/205847873-1535575f-d805-4a02-b7de-ffbcb1fe3ecc.png)

**Comment by AnnoyingVillager** [comment]
Same issue. Local m3u8 servers doesn't work. I've even tried a live m3u8 but it doesn't work as well.

**Comment by AnnoyingVillager** [comment]
> I set up an M3U8 server to stream through OBS and play it normally when using potplayer, but when I paste the url into the game, it keeps black. Does this have anything to do with coding patterns and color patterns? （Using Google Translate may cause grammatical errors） ![image](https://user-images.githubusercontent.com/114065726/205847462-64f70921-3d13-49ba-9e6b-2a4731aceebd.png) ![image](https://user-images.githubusercontent.com/114065726/205847873-1535575f-d805-4a02-b7de-ffbcb1fe3ecc.png)

我试了湖南卫视的直播流，也是黑屏，http://219.151.31.38/liveplay-kk.rtxapp.com/live/program/live/hnwshd/4000000/mnf.m3u8

**Comment by 5ur3z** [comment]
> Same issue. Local m3u8 servers doesn't work. I've even tried a live m3u8 but it doesn't work as well.

Local m3u8 servers will not work for sure，but when I use public network ip it still keeps black..

**Comment by AnnoyingVillager** [comment]
> 

Why do local m3u8 servers not work? I've tested it on chrome by implementing video.js in html files, and it worked fine. Local m3u8 servers work as the same as LAN servers, and it should have the same effect as a public server at your local network.

**Comment by AnnoyingVillager** [comment]
> > Same issue. Local m3u8 servers doesn't work. I've even tried a live m3u8 but it doesn't work as well.
> 
> Local m3u8 servers will not work for sure，but when I use public network ip it still keeps black..

Why do local m3u8 servers not work? I've tested it on chrome by implementing video.js in html files, and it worked fine. Local m3u8 servers work as the same as LAN servers, and it should have the same effect as a public server at your local network.

**Comment by 5ur3z** [comment]
> > > Same issue. Local m3u8 servers doesn't work. I've even tried a live m3u8 but it doesn't work as well.
> > 
> > 
> > Local m3u8 servers will not work for sure，but when I use public network ip it still keeps black..
> 
> Why do local m3u8 servers not work? I've tested it on chrome by implementing video.js in html files, and it worked fine. Local m3u8 servers work as the same as LAN servers, and it should have the same effect as a public server at your local network.

emm看来我刚才说的不太严谨( 
但是无论是本地还是公网IP搭建的m3u8服务器，都是黑屏
我找到一个可以被识别的m3u8链接，或许是格式的问题，只有这一小部分能被播放
https://live-hls.jstv.com/livezhuzhan/jsgg.m3u8?upt=4383b1d62510710360

**Comment by AnnoyingVillager** [comment]
> > > > Same issue. Local m3u8 servers doesn't work. I've even tried a live m3u8 but it doesn't work as well.
> > > 
> > > 
> > > Local m3u8 servers will not work for sure，but when I use public network ip it still keeps black..
> > 
> > 
> > Why do local m3u8 servers not work? I've tested it on chrome by implementing video.js in html files, and it worked fine. Local m3u8 servers work as the same as LAN servers, and it should have the same effect as a public server at your local network.
> 
> emm看来我刚才说的不太严谨( 但是无论是本地还是公网IP搭建的m3u8服务器，都是黑屏 我找到一个可以被识别的m3u8链接，或许是格式的问题，只有这一小部分能被播放 https://live-hls.jstv.com/livezhuzhan/jsgg.m3u8?upt=4383b1d62510710360

按理来说都是h264编码，都是AAC格式音频，我从河南卫视直播页面提取出来的m3u8地址就可以播放，但是不知道为什么我自己的就不行，本地服务器的图片可以正常显示，但是m3u8就不行，我甚至去找了twitch上一篇讲hls的文章照着做都没用。一开始我还以为是我用iis搭建服务器的问题，后来发现nginx也不行。我把河南卫视直播的.ts片段下载下来放到自己的服务器上，用提取的m3u8依然播放不了，真的搞不懂是什么问题了

**Comment by 5ur3z** [comment]
> My implementation of M3U8 decoder might not be compliant with the standard, I don't know how much it's different from Twitch M3U8...

Could you tell us How is the m3u8 playback function implemented? 
May be this is the source of the issue.

**Comment by mindstorm38** [comment]
I'm using an external library, as you can see in the following section:
https://github.com/mindstorm38/fabric-webstreamer/blob/fd68e0d3f43a0810d6e2c6334fac2ae99a157029/src/main/java/fr/theorozier/webstreamer/display/render/DisplayLayerHls.java#L175-L188

It's this library: https://github.com/carlanton/m3u8-parser

**Comment by 5ur3z** [comment]
This problem has been solved!
Use linux to build an SRS server after using obs push stream can be, OBS push stream to choose x264 encoder

**Comment by 5ur3z** [comment]
But there is another serious bug

When I accidentally entered the wrong link into the game, it would cause the game to crash. After entering the game again, it still crashed

I typed “tail -f./objs/srs.log”

**Comment by AnnoyingVillager** [comment]
> But there is another serious bug
> 
> When I accidentally entered the wrong link into the game, it would cause the game to crash. After entering the game again, it still crashed
> 
> I typed “tail -f./objs/srs.log”

To fix this, simply disable the mod, enter the game, replace the screen with minecraft blocks and reload the mod.

**Comment by mindstorm38** [comment]
> When I accidentally entered the wrong link into the game, it would cause the game to crash. After entering the game again, it still crashed

I believe this issue was fixed for 1.19 release of the mod. https://github.com/mindstorm38/fabric-webstreamer/commit/64a8c0cb3fee886698ce1512a50a3c2f7040f06a

My current issue is that it's really complicated for me to maintain the mod for multiple minecraft versions
