### ISSUE TITLE
Doesn't work on 1.19.2!

### ISSUE THREAD

**Issue by LonelyGuy12** [mindstorm38/fabric-webstreamer#14]
I tried using the mod in singleplayer on 1.19.2 and it doesn't seem to be working with m3u8!
![image](https://user-images.githubusercontent.com/93421108/228257787-a92b58a0-a1cf-4e91-a7a9-7509db7e9090.png)

It does work as expected with other formats

**Comment by mindstorm38** [comment]
Please read #21
