### ISSUE TITLE
[request] 1.20 port

### ISSUE THREAD

**Issue by V-lpen** [mindstorm38/fabric-webstreamer#18]
Is this planned? I love using this mod to watch streams with my friends, even if Twitch API has introduced ads back into the m3u8 format, I still enjoy watching it in game. Thanks :D

**Comment by mindstorm38** [comment]
Please read #21

**Comment by samuelh2005** [comment]
If you want to use this mod in 1.20.1 then you may use my [downgraded version](https://github.com/ajh123/fabric-webstreamer/releases/tag/1.4.0).
