### ISSUE TITLE
[request] 1.20.4 port

### ISSUE THREAD

**Issue by jstin9** [mindstorm38/fabric-webstreamer#20]
Hello, I really admire your mod. This is the best mod I have ever seen for watching broadcasts with my friends. It so happens that I wanted to put your mod on the server but the version is too old, I got sad. Is there any plans to update this wonderful mod in the near future? Thank you for your time!

**Comment by mindstorm38** [comment]
I'm currently working on it !

**Comment by mindstorm38** [comment]
I'm starting by documenting everything... Only then I'll update, for now it's more of a developer thing.

**Comment by jstin9** [comment]
No problem, thank you so much, hope it works out for you soon!
